[package]
name = "blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
bs58 = "0.5.1"
hex = "0.4.3"
p256 = { version = "0.13.2", features = ["ecdsa", "arithmetic"] }
ripemd = "0.1.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.8"
